---
# System preparation tasks for Kubernetes
# Configure hostname, disable swap and configure system settings

- name: Set hostname based on inventory
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - kubernetes
    - system-prep
    - hostname

- name: Update /etc/hosts with current hostname
  lineinfile:
    path: /etc/hosts
    regexp: "^127\\.0\\.1\\.1\\s+.*"
    line: "127.0.1.1 {{ inventory_hostname }}"
    backup: yes
  tags:
    - kubernetes
    - system-prep
    - hostname

- name: Verify hostname is set correctly
  command: hostnamectl status --static
  register: current_hostname
  changed_when: false
  tags:
    - kubernetes
    - system-prep
    - hostname
    - verify

- name: Display current hostname
  debug:
    msg: "Current hostname: {{ current_hostname.stdout }}"
  tags:
    - kubernetes
    - system-prep
    - hostname
    - verify

- name: Disable swap immediately
  command: swapoff -a
  tags:
    - kubernetes
    - system-prep

- name: Remove swap entries from fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^.*swap.*"
    state: absent
  tags:
    - kubernetes
    - system-prep

- name: Verify swap is disabled
  command: swapon --show
  register: swap_status
  failed_when: swap_status.stdout != ""
  tags:
    - kubernetes
    - system-prep
    - verify

- name: Display swap status
  debug:
    msg: "Swap status: {{ 'disabled' if swap_status.stdout == '' else 'enabled' }}"
  tags:
    - kubernetes
    - system-prep
    - verify
