---
# System preparation tasks for Kubernetes
# Disable swap and configure system settings

- name: Disable swap immediately
  command: swapoff -a
  tags:
    - kubernetes
    - system-prep

- name: Remove swap entries from fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^.*swap.*"
    state: absent
  tags:
    - kubernetes
    - system-prep

- name: Verify swap is disabled
  command: swapon --show
  register: swap_status
  failed_when: swap_status.stdout != ""
  tags:
    - kubernetes
    - system-prep
    - verify

- name: Display swap status
  debug:
    msg: "Swap status: {{ 'disabled' if swap_status.stdout == '' else 'enabled' }}"
  tags:
    - kubernetes
    - system-prep
    - verify
