---
# Configure kernel modules and sysctl settings for Kubernetes and containerd
# These settings are required for proper networking and container runtime functionality

- name: Load required kernel modules for containerd
  copy:
    content: |
      # Kernel modules required for containerd and Kubernetes networking
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: "0644"

- name: Load overlay kernel module
  modprobe:
    name: overlay
    state: present

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Configure sysctl settings for Kubernetes networking
  copy:
    content: |
      # Kubernetes networking requirements
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"

- name: Apply sysctl settings immediately
  shell: sysctl --system

- name: Verify sysctl settings are applied
  shell: |
    sysctl net.bridge.bridge-nf-call-iptables
    sysctl net.bridge.bridge-nf-call-ip6tables  
    sysctl net.ipv4.ip_forward
  register: sysctl_status
  failed_when: false

- name: Display sysctl settings
  debug:
    msg: |
      Applied sysctl settings:
      {{ sysctl_status.stdout_lines | join('\n') }}

- name: Verify kernel modules are loaded
  shell: lsmod | grep -E "(overlay|br_netfilter)"
  register: modules_loaded
  failed_when: modules_loaded.rc != 0

- name: Display loaded kernel modules
  debug:
    msg: "Loaded kernel modules: {{ modules_loaded.stdout_lines }}"
