---
- name: Configure sysctl for Kubernetes networking
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"

- name: Apply sysctl settings
  shell: sysctl --system
  become: true

- name: containerd Setup
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf

- name: Load 'overlay' module
  ansible.builtin.command:
    cmd: modprobe overlay

- name: Load 'br_netfilter' module
  ansible.builtin.command:
    cmd: modprobe br_netfilter

- name: Apply sysctl settings
  ansible.builtin.command:
    cmd: sysctl --system
