- name: Ensure NFS packages are installed
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: true

- name: Create the NFS export directory
  file:
    path: "{{ nfs_export_directory }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "0777"

- name: Configure NFS exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"

- name: Apply NFS export configuration
  command: exportfs -rav
  notify:
    - Restart NFS server

- name: Ensure NFS service is enabled and running
  service:
    name: nfs-server
    enabled: true
    state: started
