---
# Alternative implementation using individual sysctl tasks for better idempotency
# This approach allows Ansible to properly track changes

- name: Create kernel modules configuration for containerd
  copy:
    content: |
      # Kernel modules required for containerd and Kubernetes networking
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: "0644"
  tags:
    - containerd
    - kernel

- name: Load overlay kernel module
  modprobe:
    name: overlay
    state: present
  tags:
    - containerd
    - kernel

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present
  tags:
    - containerd
    - kernel

- name: Configure net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  tags:
    - containerd
    - kernel
    - networking

- name: Configure net.bridge.bridge-nf-call-ip6tables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  tags:
    - containerd
    - kernel
    - networking

- name: Configure net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  tags:
    - containerd
    - kernel
    - networking

- name: Verify kernel modules are loaded
  shell: lsmod | grep -E "(overlay|br_netfilter)"
  register: modules_loaded
  failed_when: modules_loaded.rc != 0
  tags:
    - containerd
    - kernel
    - verify

- name: Display loaded kernel modules
  debug:
    msg: "Loaded kernel modules: {{ modules_loaded.stdout_lines }}"
  tags:
    - containerd
    - kernel
    - verify

- name: Verify sysctl settings
  shell: |
    sysctl net.bridge.bridge-nf-call-iptables
    sysctl net.bridge.bridge-nf-call-ip6tables  
    sysctl net.ipv4.ip_forward
  register: sysctl_verification
  changed_when: false
  tags:
    - containerd
    - kernel
    - verify

- name: Display sysctl verification
  debug:
    msg: |
      Current sysctl settings:
      {{ sysctl_verification.stdout_lines | join('\n') }}
  tags:
    - containerd
    - kernel
    - verify
