---
# Configure kernel modules required for containerd and Kubernetes

- name: Create kernel modules configuration for containerd
  copy:
    content: |
      # Kernel modules required for containerd and Kubernetes networking
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: "0644"
  tags:
    - containerd
    - kernel

- name: Load overlay kernel module
  modprobe:
    name: overlay
    state: present
  tags:
    - containerd
    - kernel

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present
  tags:
    - containerd
    - kernel

- name: Configure sysctl settings for Kubernetes networking
  copy:
    content: |
      # Kubernetes networking requirements
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"
  tags:
    - containerd
    - kernel
    - networking

- name: Apply sysctl settings immediately
  sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  tags:
    - containerd
    - kernel
    - networking

- name: Verify kernel modules are loaded
  shell: lsmod | grep -E "(overlay|br_netfilter)"
  register: modules_loaded
  failed_when: modules_loaded.rc != 0
  tags:
    - containerd
    - kernel
    - verify

- name: Display loaded kernel modules
  debug:
    msg: "Loaded kernel modules: {{ modules_loaded.stdout_lines }}"
  tags:
    - containerd
    - kernel
    - verify
